pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat './mvnw clean package -DskipTests=true'
            }
            steps {
                bat './mvnw clean package -DskipTests=true'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}